export { DashboardWidget } from './DashboardWidget'
export { DashboardView } from './DashboardView'
export { DashboardList } from './DashboardList'
export { DashboardPreview } from './DashboardPreview'
export { MetricWidget } from './MetricWidget'
export { ChartWidget } from './ChartWidget'
export { TableWidget } from './TableWidget'
export { InsightWidget } from './InsightWidget'
export { InsightCard } from './InsightCard'
export { WidgetPreviewCard } from './WidgetPreviewCard'
export { WidgetWrapper } from './WidgetWrapper'

// New widget-related components
export { AddWidgetDialog } from './AddWidgetDialog'
export { ExplorationTopicAccordion } from './ExplorationTopicAccordion'

export { widgetsByExplorationTopic, getWidgetsByExplorationTopic } from './widgetTemplatesByTopic'
export type { WidgetTemplate, ExplorationTopic } from './widgetTemplatesByTopic'
export type { DashboardWidgetData } from './DashboardWidget'
export type { Dashboard } from './DashboardList' 